name = "easytier-ws-relay"
main = "src/worker.js"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[vars]
WS_PATH = "ws"
EASYTIER_DISABLE_RELAY = "1"
EASYTIER_COMPRESS_RPC = "1"

[durable_objects]
bindings = [

]

[[migrations]]
tag = "v1"
